"""payments webhooks reconciliation chargebacks payout eta

Revision ID: 12b5dff5515e
Revises: cc6512f38e47
Create Date: 2026-10-07 15:53:48.182524
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '12b5dff5515e'
down_revision = 'cc6512f38e47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_batches',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mismatches', sa.BigInteger(), nullable=False),
    sa.Column('run_by', sa.String(length=60), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_batches')),
    sa.UniqueConstraint('day', name=op.f('uq_reconciliation_batches_day')),
    schema='payments'
    )
    op.create_table('webhook_events',
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('event_id', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events')),
    sa.UniqueConstraint('provider', 'event_id', name='uq_webhook_provider_event'),
    schema='payments'
    )
    op.add_column('payment_intents', sa.Column('charged_back_at', sa.DateTime(timezone=True), nullable=True), schema='payments')
    op.add_column('payment_intents', sa.Column('chargeback_minor', sa.BigInteger(), nullable=True), schema='payments')
    op.add_column('payment_intents', sa.Column('chargeback_reason', sa.String(length=200), nullable=True), schema='payments')
    op.add_column('payouts', sa.Column('expected_at', sa.DateTime(timezone=True), nullable=True), schema='payments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payouts', 'expected_at', schema='payments')
    op.drop_column('payment_intents', 'chargeback_reason', schema='payments')
    op.drop_column('payment_intents', 'chargeback_minor', schema='payments')
    op.drop_column('payment_intents', 'charged_back_at', schema='payments')
    op.drop_table('webhook_events', schema='payments')
    op.drop_table('reconciliation_batches', schema='payments')
    # ### end Alembic commands ###
