"""identity partner name, resume link and reason

Revision ID: 1f119dc68610
Revises: f1360ce42a96
Create Date: 2026-10-09 12:27:12.013192
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '1f119dc68610'
down_revision = 'f1360ce42a96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_sessions', sa.Column('provider', sa.String(length=20), nullable=True), schema='verification')
    op.add_column('provider_sessions', sa.Column('hosted_url', sa.String(length=1000), nullable=True), schema='verification')
    op.add_column('provider_sessions', sa.Column('reason', sa.String(length=300), nullable=True), schema='verification')
    # ### end Alembic commands ###
    op.execute("UPDATE verification.provider_sessions SET provider = 'persona' WHERE provider IS NULL")  # sessions before Veriff


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_sessions', 'reason', schema='verification')
    op.drop_column('provider_sessions', 'hosted_url', schema='verification')
    op.drop_column('provider_sessions', 'provider', schema='verification')
    # ### end Alembic commands ###
