"""saved professionals

Revision ID: 2eb440dab54e
Revises: 9613b92f7cb3
Create Date: 2026-10-05 17:15:48.319632
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '2eb440dab54e'
down_revision = '9613b92f7cb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_professionals',
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_professionals')),
    sa.UniqueConstraint('identity_id', 'professional_id', name=op.f('uq_saved_professionals_identity_id_professional_id')),
    schema='marketplace'
    )
    op.create_index(op.f('ix_marketplace_saved_professionals_identity_id'), 'saved_professionals', ['identity_id'], unique=False, schema='marketplace')
    op.create_index(op.f('ix_marketplace_saved_professionals_professional_id'), 'saved_professionals', ['professional_id'], unique=False, schema='marketplace')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketplace_saved_professionals_professional_id'), table_name='saved_professionals', schema='marketplace')
    op.drop_index(op.f('ix_marketplace_saved_professionals_identity_id'), table_name='saved_professionals', schema='marketplace')
    op.drop_table('saved_professionals', schema='marketplace')
    # ### end Alembic commands ###
