"""verification cases and trust profiles

Revision ID: 33d8bb2d0f0e
Revises: f7f280be35f1
Create Date: 2026-10-05 15:59:14.070556
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '33d8bb2d0f0e'
down_revision = 'f7f280be35f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    for schema in ("verification", "trust"):
        op.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.String(length=1), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('flags', postgresql.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('engagement_suspended', sa.Boolean(), nullable=False),
    sa.Column('recomputed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles')),
    sa.UniqueConstraint('professional_id', name=op.f('uq_profiles_professional_id')),
    schema='trust'
    )
    op.create_table('signals',
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('source_event_type', sa.String(length=120), nullable=False),
    sa.Column('signal_type', sa.String(length=30), nullable=False),
    sa.Column('adverse', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals')),
    sa.UniqueConstraint('professional_id', 'source_event_id', name=op.f('uq_signals_professional_id_source_event_id')),
    schema='trust'
    )
    op.create_index(op.f('ix_trust_signals_professional_id'), 'signals', ['professional_id'], unique=False, schema='trust')
    op.create_table('tier_history',
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('from_tier', sa.String(length=1), nullable=False),
    sa.Column('to_tier', sa.String(length=1), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_event_type', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tier_history')),
    schema='trust'
    )
    op.create_index(op.f('ix_trust_tier_history_professional_id'), 'tier_history', ['professional_id'], unique=False, schema='trust')
    op.create_table('cases',
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('owner_identity_id', sa.UUID(), nullable=False),
    sa.Column('verification_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('jurisdiction', sa.String(length=10), nullable=True),
    sa.Column('credential_claim_id', sa.UUID(), nullable=True),
    sa.Column('specialization', sa.String(length=120), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider_result', sa.String(length=20), nullable=True),
    sa.Column('estimated_completion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason_code', sa.String(length=60), nullable=True),
    sa.Column('public_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases')),
    sa.UniqueConstraint('credential_claim_id', name=op.f('uq_cases_credential_claim_id')),
    schema='verification'
    )
    op.create_index('ix_cases_queue', 'cases', ['status', 'created_at'], unique=False, schema='verification')
    op.create_index('ix_cases_subject', 'cases', ['subject_type', 'subject_id'], unique=False, schema='verification')
    op.create_table('evidence_items',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(length=40), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['verification.cases.id'], name=op.f('fk_evidence_items_case_id_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_items')),
    schema='verification'
    )
    op.create_index(op.f('ix_verification_evidence_items_case_id'), 'evidence_items', ['case_id'], unique=False, schema='verification')
    # ### end Alembic commands ###

    # Evidence is insert-only: reject UPDATE/DELETE at the database level (EP-05).
    from zoikorum.shared.ddl import append_only_trigger
    for stmt in append_only_trigger("verification.evidence_items"):
        op.execute(stmt)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_evidence_items_case_id'), table_name='evidence_items', schema='verification')
    op.drop_table('evidence_items', schema='verification')
    op.drop_index('ix_cases_subject', table_name='cases', schema='verification')
    op.drop_index('ix_cases_queue', table_name='cases', schema='verification')
    op.drop_table('cases', schema='verification')
    op.drop_index(op.f('ix_trust_tier_history_professional_id'), table_name='tier_history', schema='trust')
    op.drop_table('tier_history', schema='trust')
    op.drop_index(op.f('ix_trust_signals_professional_id'), table_name='signals', schema='trust')
    op.drop_table('signals', schema='trust')
    op.drop_table('profiles', schema='trust')
    # ### end Alembic commands ###
