"""customer portal: profile, data requests, billing contacts, collections, notification preferences

Revision ID: 39eff2ff7220
Revises: 6d498fbcfc06
Create Date: 2026-10-06 08:50:19.924675
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '39eff2ff7220'
down_revision = '6d498fbcfc06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE SCHEMA IF NOT EXISTS "notification"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections')),
    sa.UniqueConstraint('identity_id', 'name', name=op.f('uq_collections_identity_id_name')),
    schema='marketplace'
    )
    op.create_index(op.f('ix_marketplace_collections_identity_id'), 'collections', ['identity_id'], unique=False, schema='marketplace')
    op.create_table('preferences',
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Boolean(), nullable=False),
    sa.Column('in_app', sa.Boolean(), nullable=False),
    sa.Column('sms', sa.Boolean(), nullable=False),
    sa.Column('marketing', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preferences')),
    sa.UniqueConstraint('identity_id', name=op.f('uq_preferences_identity_id')),
    schema='notification'
    )
    op.create_table('billing_contacts',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['buyer.organizations.id'], name=op.f('fk_billing_contacts_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_contacts')),
    sa.UniqueConstraint('organization_id', 'identity_id', name=op.f('uq_billing_contacts_organization_id_identity_id')),
    schema='buyer'
    )
    op.create_index(op.f('ix_buyer_billing_contacts_organization_id'), 'billing_contacts', ['organization_id'], unique=False, schema='buyer')
    op.create_table('data_requests',
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.identities.id'], name=op.f('fk_data_requests_identity_id_identities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_requests')),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_data_requests_identity_id'), 'data_requests', ['identity_id'], unique=False, schema='identity')
    op.create_table('collection_items',
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['marketplace.collections.id'], name=op.f('fk_collection_items_collection_id_collections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_items')),
    sa.UniqueConstraint('collection_id', 'professional_id', name=op.f('uq_collection_items_collection_id_professional_id')),
    schema='marketplace'
    )
    op.create_index(op.f('ix_marketplace_collection_items_collection_id'), 'collection_items', ['collection_id'], unique=False, schema='marketplace')
    op.create_index(op.f('ix_marketplace_collection_items_professional_id'), 'collection_items', ['professional_id'], unique=False, schema='marketplace')
    op.add_column('organizations', sa.Column('industry', sa.String(length=80), nullable=True), schema='buyer')
    op.add_column('organizations', sa.Column('time_zone', sa.String(length=64), nullable=True), schema='buyer')
    op.add_column('identities', sa.Column('phone_enc', sa.String(length=500), nullable=True), schema='identity')
    op.add_column('identities', sa.Column('language', sa.String(length=10), server_default='en', nullable=False), schema='identity')
    op.add_column('identities', sa.Column('time_zone', sa.String(length=64), nullable=True), schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identities', 'time_zone', schema='identity')
    op.drop_column('identities', 'language', schema='identity')
    op.drop_column('identities', 'phone_enc', schema='identity')
    op.drop_column('organizations', 'time_zone', schema='buyer')
    op.drop_column('organizations', 'industry', schema='buyer')
    op.drop_index(op.f('ix_marketplace_collection_items_professional_id'), table_name='collection_items', schema='marketplace')
    op.drop_index(op.f('ix_marketplace_collection_items_collection_id'), table_name='collection_items', schema='marketplace')
    op.drop_table('collection_items', schema='marketplace')
    op.drop_index(op.f('ix_identity_data_requests_identity_id'), table_name='data_requests', schema='identity')
    op.drop_table('data_requests', schema='identity')
    op.drop_index(op.f('ix_buyer_billing_contacts_organization_id'), table_name='billing_contacts', schema='buyer')
    op.drop_table('billing_contacts', schema='buyer')
    op.drop_table('preferences', schema='notification')
    op.drop_index(op.f('ix_marketplace_collections_identity_id'), table_name='collections', schema='marketplace')
    op.drop_table('collections', schema='marketplace')
    # ### end Alembic commands ###
