"""proposal attachments

Revision ID: 41e86365a15a
Revises: 935acaf8cfd4
Create Date: 2026-10-08 16:20:28.428948
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '41e86365a15a'
down_revision = '935acaf8cfd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False), schema='proposal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'attachments', schema='proposal')
    # ### end Alembic commands ###
