"""escrow and payments

Revision ID: 50b4309ca1b3
Revises: 9b3f7bed833e
Create Date: 2026-10-06 15:40:58.891394
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '50b4309ca1b3'
down_revision = '9b3f7bed833e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE SCHEMA IF NOT EXISTS "escrow"')
    op.execute('CREATE SCHEMA IF NOT EXISTS "payments"')
    op.execute('CREATE SEQUENCE IF NOT EXISTS payments.invoice_number_seq')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_minor', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('funded_minor', sa.BigInteger(), nullable=False),
    sa.Column('held_minor', sa.BigInteger(), nullable=False),
    sa.Column('on_hold_minor', sa.BigInteger(), nullable=False),
    sa.Column('released_minor', sa.BigInteger(), nullable=False),
    sa.Column('refunded_minor', sa.BigInteger(), nullable=False),
    sa.Column('fees_minor', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('contract_id', name=op.f('uq_accounts_contract_id')),
    schema='escrow'
    )
    op.create_index(op.f('ix_escrow_accounts_organization_id'), 'accounts', ['organization_id'], unique=False, schema='escrow')
    op.create_index(op.f('ix_escrow_accounts_professional_id'), 'accounts', ['professional_id'], unique=False, schema='escrow')
    op.create_table('invoices',
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('release_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.UUID(), nullable=True),
    sa.Column('lines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tax_minor', sa.BigInteger(), nullable=False),
    sa.Column('total_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('number', name=op.f('uq_invoices_number')),
    sa.UniqueConstraint('release_id', name=op.f('uq_invoices_release_id')),
    schema='payments'
    )
    op.create_index('ix_invoices_org', 'invoices', ['organization_id', 'created_at'], unique=False, schema='payments')
    op.create_table('payment_intents',
    sa.Column('funding_id', sa.UUID(), nullable=False),
    sa.Column('escrow_account_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_ref', sa.String(length=100), nullable=True),
    sa.Column('method_label', sa.String(length=80), nullable=False),
    sa.Column('failure_code', sa.String(length=60), nullable=True),
    sa.Column('failure_message', sa.String(length=300), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_intents')),
    sa.UniqueConstraint('funding_id', name=op.f('uq_payment_intents_funding_id')),
    schema='payments'
    )
    op.create_index(op.f('ix_payments_payment_intents_organization_id'), 'payment_intents', ['organization_id'], unique=False, schema='payments')
    op.create_table('payout_accounts',
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('holder_name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_account_ref', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payout_accounts')),
    sa.UniqueConstraint('professional_id', name=op.f('uq_payout_accounts_professional_id')),
    schema='payments'
    )
    op.create_table('payouts',
    sa.Column('release_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.UUID(), nullable=True),
    sa.Column('gross_minor', sa.BigInteger(), nullable=False),
    sa.Column('fee_minor', sa.BigInteger(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_ref', sa.String(length=100), nullable=True),
    sa.Column('failure_message', sa.String(length=300), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payouts')),
    sa.UniqueConstraint('release_id', name=op.f('uq_payouts_release_id')),
    schema='payments'
    )
    op.create_index('ix_payouts_professional', 'payouts', ['professional_id', 'created_at'], unique=False, schema='payments')
    op.create_table('allocations',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('funding_id', sa.UUID(), nullable=True),
    sa.Column('released_minor', sa.BigInteger(), nullable=False),
    sa.Column('fee_minor', sa.BigInteger(), nullable=False),
    sa.Column('refunded_minor', sa.BigInteger(), nullable=False),
    sa.Column('funded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['escrow.accounts.id'], name=op.f('fk_allocations_account_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allocations')),
    sa.UniqueConstraint('milestone_id', name=op.f('uq_allocations_milestone_id')),
    schema='escrow'
    )
    op.create_index(op.f('ix_escrow_allocations_account_id'), 'allocations', ['account_id'], unique=False, schema='escrow')
    op.create_table('fundings',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('milestone_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_message', sa.String(length=300), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['escrow.accounts.id'], name=op.f('fk_fundings_account_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fundings')),
    schema='escrow'
    )
    op.create_index('ix_fundings_account', 'fundings', ['account_id', 'created_at'], unique=False, schema='escrow')
    op.create_table('ledger_entries',
    sa.Column('entry_group_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.String(length=30), nullable=False),
    sa.Column('ledger_account', sa.String(length=30), nullable=False),
    sa.Column('debit_minor', sa.BigInteger(), nullable=False),
    sa.Column('credit_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reference_type', sa.String(length=30), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.UUID(), nullable=True),
    sa.Column('memo', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['escrow.accounts.id'], name=op.f('fk_ledger_entries_account_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries')),
    schema='escrow'
    )
    op.create_index('ix_ledger_account', 'ledger_entries', ['account_id', 'created_at'], unique=False, schema='escrow')
    op.create_index('ix_ledger_group', 'ledger_entries', ['entry_group_id'], unique=False, schema='escrow')
    op.create_table('releases',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.UUID(), nullable=False),
    sa.Column('gross_minor', sa.BigInteger(), nullable=False),
    sa.Column('fee_minor', sa.BigInteger(), nullable=False),
    sa.Column('net_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fee_bps', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['escrow.accounts.id'], name=op.f('fk_releases_account_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_releases')),
    sa.UniqueConstraint('milestone_id', name=op.f('uq_releases_milestone_id')),
    schema='escrow'
    )
    op.create_index(op.f('ix_escrow_releases_account_id'), 'releases', ['account_id'], unique=False, schema='escrow')
    # ### end Alembic commands ###

    # The escrow ledger is insert-only: reject UPDATE/DELETE at the database level (EP-05).
    from zoikorum.shared.ddl import append_only_trigger
    for stmt in append_only_trigger("escrow.ledger_entries"):
        op.execute(stmt)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_escrow_releases_account_id'), table_name='releases', schema='escrow')
    op.drop_table('releases', schema='escrow')
    op.drop_index('ix_ledger_group', table_name='ledger_entries', schema='escrow')
    op.drop_index('ix_ledger_account', table_name='ledger_entries', schema='escrow')
    op.drop_table('ledger_entries', schema='escrow')
    op.drop_index('ix_fundings_account', table_name='fundings', schema='escrow')
    op.drop_table('fundings', schema='escrow')
    op.drop_index(op.f('ix_escrow_allocations_account_id'), table_name='allocations', schema='escrow')
    op.drop_table('allocations', schema='escrow')
    op.drop_index('ix_payouts_professional', table_name='payouts', schema='payments')
    op.drop_table('payouts', schema='payments')
    op.drop_table('payout_accounts', schema='payments')
    op.drop_index(op.f('ix_payments_payment_intents_organization_id'), table_name='payment_intents', schema='payments')
    op.drop_table('payment_intents', schema='payments')
    op.drop_index('ix_invoices_org', table_name='invoices', schema='payments')
    op.drop_table('invoices', schema='payments')
    op.drop_index(op.f('ix_escrow_accounts_professional_id'), table_name='accounts', schema='escrow')
    op.drop_index(op.f('ix_escrow_accounts_organization_id'), table_name='accounts', schema='escrow')
    op.drop_table('accounts', schema='escrow')
    op.execute('DROP SEQUENCE IF EXISTS payments.invoice_number_seq')
    # ### end Alembic commands ###
