"""email confirmation resend time

Revision ID: 68fb966363b4
Revises: 1f119dc68610
Create Date: 2026-10-09 12:57:33.634585
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '68fb966363b4'
down_revision = '1f119dc68610'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identities', sa.Column('confirmation_requested_at', sa.DateTime(timezone=True), nullable=True), schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identities', 'confirmation_requested_at', schema='identity')
    # ### end Alembic commands ###
