"""profile photo

Revision ID: 6d498fbcfc06
Revises: d94dfd86d326
Create Date: 2026-10-05 18:45:56.469436
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '6d498fbcfc06'
down_revision = 'd94dfd86d326'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professionals', sa.Column('photo_key', sa.String(length=200), nullable=True), schema='professional')
    op.add_column('professionals', sa.Column('photo_content_type', sa.String(length=30), nullable=True), schema='professional')
    op.add_column('professionals', sa.Column('photo_sha256', sa.String(length=64), nullable=True), schema='professional')
    op.add_column('professional_documents', sa.Column('photo_url', sa.String(length=200), nullable=True), schema='search')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professional_documents', 'photo_url', schema='search')
    op.drop_column('professionals', 'photo_sha256', schema='professional')
    op.drop_column('professionals', 'photo_content_type', schema='professional')
    op.drop_column('professionals', 'photo_key', schema='professional')
    # ### end Alembic commands ###
