"""organizations and firms

Revision ID: 8b68282be96e
Revises: f40309763a19
Create Date: 2026-10-05 13:31:20.317647
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '8b68282be96e'
down_revision = 'f40309763a19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    for schema in ("buyer", "firm"):
        op.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('org_type', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('business_context', sa.String(length=30), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    schema='buyer'
    )
    op.create_index(op.f('ix_buyer_organizations_created_by'), 'organizations', ['created_by'], unique=False, schema='buyer')
    op.create_table('firms',
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('trading_name', sa.String(length=200), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('hq_country', sa.String(length=2), nullable=False),
    sa.Column('size_band', sa.String(length=10), nullable=True),
    sa.Column('primary_category', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_firms')),
    schema='firm'
    )
    op.create_index(op.f('ix_firm_firms_created_by'), 'firms', ['created_by'], unique=False, schema='firm')
    op.create_table('business_units',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['buyer.organizations.id'], name=op.f('fk_business_units_organization_id_organizations')),
    sa.ForeignKeyConstraint(['parent_id'], ['buyer.business_units.id'], name=op.f('fk_business_units_parent_id_business_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_units')),
    sa.UniqueConstraint('organization_id', 'name', name=op.f('uq_business_units_organization_id_name')),
    schema='buyer'
    )
    op.create_index(op.f('ix_buyer_business_units_organization_id'), 'business_units', ['organization_id'], unique=False, schema='buyer')
    op.create_table('invitations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('spend_limit_minor', sa.BigInteger(), nullable=True),
    sa.Column('spend_limit_currency', sa.String(length=3), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['buyer.organizations.id'], name=op.f('fk_invitations_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitations')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_invitations_token_hash')),
    schema='buyer'
    )
    op.create_index(op.f('ix_buyer_invitations_organization_id'), 'invitations', ['organization_id'], unique=False, schema='buyer')
    op.create_index('ix_invitations_pending_email', 'invitations', ['email'], unique=False, schema='buyer', postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('members',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('spend_limit_minor', sa.BigInteger(), nullable=True),
    sa.Column('spend_limit_currency', sa.String(length=3), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['buyer.organizations.id'], name=op.f('fk_members_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_members')),
    sa.UniqueConstraint('organization_id', 'identity_id', name=op.f('uq_members_organization_id_identity_id')),
    schema='buyer'
    )
    op.create_index(op.f('ix_buyer_members_identity_id'), 'members', ['identity_id'], unique=False, schema='buyer')
    op.create_index(op.f('ix_buyer_members_organization_id'), 'members', ['organization_id'], unique=False, schema='buyer')
    op.create_table('invitations',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.firms.id'], name=op.f('fk_invitations_firm_id_firms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitations')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_invitations_token_hash')),
    schema='firm'
    )
    op.create_index(op.f('ix_firm_invitations_firm_id'), 'invitations', ['firm_id'], unique=False, schema='firm')
    op.create_index('ix_firm_invitations_pending_email', 'invitations', ['email'], unique=False, schema='firm', postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('members',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.firms.id'], name=op.f('fk_members_firm_id_firms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_members')),
    sa.UniqueConstraint('firm_id', 'identity_id', name=op.f('uq_members_firm_id_identity_id')),
    schema='firm'
    )
    op.create_index(op.f('ix_firm_members_firm_id'), 'members', ['firm_id'], unique=False, schema='firm')
    op.create_index(op.f('ix_firm_members_identity_id'), 'members', ['identity_id'], unique=False, schema='firm')
    op.create_table('cost_centers',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('quarterly_budget_minor', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_unit_id'], ['buyer.business_units.id'], name=op.f('fk_cost_centers_business_unit_id_business_units')),
    sa.ForeignKeyConstraint(['organization_id'], ['buyer.organizations.id'], name=op.f('fk_cost_centers_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_centers')),
    sa.UniqueConstraint('organization_id', 'code', name=op.f('uq_cost_centers_organization_id_code')),
    schema='buyer'
    )
    op.create_index(op.f('ix_buyer_cost_centers_organization_id'), 'cost_centers', ['organization_id'], unique=False, schema='buyer')
    op.add_column('identity_links', sa.Column('target_kind', sa.String(length=20), nullable=True), schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identity_links', 'target_kind', schema='identity')
    op.drop_index(op.f('ix_buyer_cost_centers_organization_id'), table_name='cost_centers', schema='buyer')
    op.drop_table('cost_centers', schema='buyer')
    op.drop_index(op.f('ix_firm_members_identity_id'), table_name='members', schema='firm')
    op.drop_index(op.f('ix_firm_members_firm_id'), table_name='members', schema='firm')
    op.drop_table('members', schema='firm')
    op.drop_index('ix_firm_invitations_pending_email', table_name='invitations', schema='firm', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index(op.f('ix_firm_invitations_firm_id'), table_name='invitations', schema='firm')
    op.drop_table('invitations', schema='firm')
    op.drop_index(op.f('ix_buyer_members_organization_id'), table_name='members', schema='buyer')
    op.drop_index(op.f('ix_buyer_members_identity_id'), table_name='members', schema='buyer')
    op.drop_table('members', schema='buyer')
    op.drop_index('ix_invitations_pending_email', table_name='invitations', schema='buyer', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index(op.f('ix_buyer_invitations_organization_id'), table_name='invitations', schema='buyer')
    op.drop_table('invitations', schema='buyer')
    op.drop_index(op.f('ix_buyer_business_units_organization_id'), table_name='business_units', schema='buyer')
    op.drop_table('business_units', schema='buyer')
    op.drop_index(op.f('ix_firm_firms_created_by'), table_name='firms', schema='firm')
    op.drop_table('firms', schema='firm')
    op.drop_index(op.f('ix_buyer_organizations_created_by'), table_name='organizations', schema='buyer')
    op.drop_table('organizations', schema='buyer')
    # ### end Alembic commands ###
