"""specialization suggestions and more taxonomy categories

Revision ID: 935acaf8cfd4
Revises: a57b42b1648c
Create Date: 2026-10-08 11:53:09.730734
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from zoikorum.domains.marketplace.taxonomy_data import default_taxonomy_rows


revision = '935acaf8cfd4'
down_revision = 'a57b42b1648c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialization_suggestions',
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_slug', sa.String(length=120), nullable=True),
    sa.Column('group_slug', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('credential_likely', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_slug', sa.String(length=120), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specialization_suggestions')),
    schema='marketplace'
    )
    op.create_index(op.f('ix_marketplace_specialization_suggestions_identity_id'), 'specialization_suggestions', ['identity_id'], unique=False, schema='marketplace')
    op.create_index(op.f('ix_marketplace_specialization_suggestions_professional_id'), 'specialization_suggestions', ['professional_id'], unique=False, schema='marketplace')
    # ### end Alembic commands ###
    _seed_new_categories()


def _seed_new_categories() -> None:
    """Reference data: the starter categories added next to Finance & Accounting (stable uuid5 ids; existing rows untouched)."""
    nodes = sa.table(
        'taxonomy_nodes',
        *(sa.column(c) for c in ('id', 'slug', 'name', 'level', 'parent_id', 'category_slug', 'sort_order', 'requires_credential',
                                 'regulated', 'requires_insurance', 'deliverable_templates', 'credential_hints', 'status',
                                 'taxonomy_version')),
        schema='marketplace',
    )
    columns = set(nodes.c.keys())
    for row in default_taxonomy_rows():
        values = {k: v for k, v in row.items() if k in columns}
        op.execute(postgresql.insert(nodes).values(**values).on_conflict_do_nothing(index_elements=['slug']))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketplace_specialization_suggestions_professional_id'), table_name='specialization_suggestions', schema='marketplace')
    op.drop_index(op.f('ix_marketplace_specialization_suggestions_identity_id'), table_name='specialization_suggestions', schema='marketplace')
    op.drop_table('specialization_suggestions', schema='marketplace')
    # ### end Alembic commands ###
