"""search professional documents

Revision ID: 9613b92f7cb3
Revises: 33d8bb2d0f0e
Create Date: 2026-10-05 16:38:48.486471
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '9613b92f7cb3'
down_revision = '33d8bb2d0f0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE SCHEMA IF NOT EXISTS "search"')
    # Fill the projection afterwards with: python -m zoikorum.cli reindex-search
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional_documents',
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('visibility_reduced', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('headline', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('years_experience_band', sa.String(length=10), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.String(length=120)), nullable=False),
    sa.Column('primary_specialization', sa.String(length=120), nullable=True),
    sa.Column('specializations', postgresql.ARRAY(sa.String(length=120)), nullable=False),
    sa.Column('specialization_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('engagement_types', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('delivery_modes', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('pricing_models', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('served_jurisdictions', postgresql.ARRAY(sa.String(length=2)), nullable=False),
    sa.Column('licensed_jurisdictions', postgresql.ARRAY(sa.String(length=2)), nullable=False),
    sa.Column('tier', sa.String(length=1), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verified_credentials', postgresql.ARRAY(sa.String(length=200)), nullable=False),
    sa.Column('offering_titles', postgresql.ARRAY(sa.String(length=150)), nullable=False),
    sa.Column('starting_price_minor', sa.BigInteger(), nullable=True),
    sa.Column('price_currency', sa.String(length=3), nullable=True),
    sa.Column('bio_excerpt', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document', postgresql.TSVECTOR(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professional_documents')),
    sa.UniqueConstraint('professional_id', name=op.f('uq_professional_documents_professional_id')),
    schema='search'
    )
    op.create_index('ix_professional_documents_document', 'professional_documents', ['document'], unique=False, schema='search', postgresql_using='gin')
    op.create_index('ix_professional_documents_specializations', 'professional_documents', ['specializations'], unique=False, schema='search', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_professional_documents_specializations', table_name='professional_documents', schema='search', postgresql_using='gin')
    op.drop_index('ix_professional_documents_document', table_name='professional_documents', schema='search', postgresql_using='gin')
    op.drop_table('professional_documents', schema='search')
    # ### end Alembic commands ###
