"""contracts: contracts, milestones, signatures, submissions

Revision ID: 9b3f7bed833e
Revises: d4e6bc59f94f
Create Date: 2026-10-06 14:17:56.275447
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '9b3f7bed833e'
down_revision = 'd4e6bc59f94f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE SCHEMA IF NOT EXISTS "contract"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('buyer_identity_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('engagement_type', sa.String(length=20), nullable=False),
    sa.Column('pricing_model', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_minor', sa.BigInteger(), nullable=False),
    sa.Column('terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('terms_hash', sa.String(length=64), nullable=False),
    sa.Column('contract_version', sa.Integer(), nullable=False),
    sa.Column('parties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nda_required', sa.Boolean(), nullable=False),
    sa.Column('document', sa.Text(), nullable=False),
    sa.Column('document_sha256', sa.String(length=64), nullable=False),
    sa.Column('policy_version_label', sa.String(length=80), nullable=False),
    sa.Column('signature_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts')),
    sa.UniqueConstraint('proposal_id', name=op.f('uq_contracts_proposal_id')),
    sa.UniqueConstraint('reference', name=op.f('uq_contracts_reference')),
    schema='contract'
    )
    op.create_index('ix_contracts_org', 'contracts', ['organization_id', 'created_at'], unique=False, schema='contract')
    op.create_index('ix_contracts_professional', 'contracts', ['professional_id', 'created_at'], unique=False, schema='contract')
    op.create_table('milestones',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('deliverable_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acceptance_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by', sa.UUID(), nullable=True),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('last_revision_reason', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.contracts.id'], name=op.f('fk_milestones_contract_id_contracts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestones')),
    sa.UniqueConstraint('contract_id', 'sequence', name=op.f('uq_milestones_contract_id_sequence')),
    schema='contract'
    )
    op.create_index(op.f('ix_contract_milestones_contract_id'), 'milestones', ['contract_id'], unique=False, schema='contract')
    op.create_table('signatures',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('contract_version', sa.Integer(), nullable=False),
    sa.Column('party', sa.String(length=20), nullable=False),
    sa.Column('signer_identity_id', sa.UUID(), nullable=False),
    sa.Column('signer_name', sa.String(length=200), nullable=False),
    sa.Column('terms_hash', sa.String(length=64), nullable=False),
    sa.Column('auth_strength', sa.String(length=20), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.contracts.id'], name=op.f('fk_signatures_contract_id_contracts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signatures')),
    sa.UniqueConstraint('contract_id', 'contract_version', 'party', name=op.f('uq_signatures_contract_id_contract_version_party')),
    schema='contract'
    )
    op.create_index(op.f('ix_contract_signatures_contract_id'), 'signatures', ['contract_id'], unique=False, schema='contract')
    op.create_table('submissions',
    sa.Column('milestone_id', sa.UUID(), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('note', sa.String(length=2000), nullable=False),
    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['contract.milestones.id'], name=op.f('fk_submissions_milestone_id_milestones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submissions')),
    schema='contract'
    )
    op.create_index(op.f('ix_contract_submissions_milestone_id'), 'submissions', ['milestone_id'], unique=False, schema='contract')
    # ### end Alembic commands ###

    # Signatures are insert-only receipts: reject UPDATE/DELETE at the database level (EP-05).
    from zoikorum.shared.ddl import append_only_trigger
    for stmt in append_only_trigger("contract.signatures"):
        op.execute(stmt)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_submissions_milestone_id'), table_name='submissions', schema='contract')
    op.drop_table('submissions', schema='contract')
    op.drop_index(op.f('ix_contract_signatures_contract_id'), table_name='signatures', schema='contract')
    op.drop_table('signatures', schema='contract')
    op.drop_index(op.f('ix_contract_milestones_contract_id'), table_name='milestones', schema='contract')
    op.drop_table('milestones', schema='contract')
    op.drop_index('ix_contracts_professional', table_name='contracts', schema='contract')
    op.drop_index('ix_contracts_org', table_name='contracts', schema='contract')
    op.drop_table('contracts', schema='contract')
    # ### end Alembic commands ###
