"""appeals partial acceptance retainer cycles duplicates weekly hours

Revision ID: a57b42b1648c
Revises: 12b5dff5515e
Create Date: 2026-10-08 09:57:13.990717
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a57b42b1648c'
down_revision = '12b5dff5515e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duplicate_suspicions',
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('other_identity_id', sa.UUID(), nullable=False),
    sa.Column('signal', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_answer', sa.String(length=20), nullable=True),
    sa.Column('user_note', sa.String(length=500), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.String(length=500), nullable=True),
    sa.Column('kept_identity_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duplicate_suspicions')),
    sa.UniqueConstraint('identity_id', 'other_identity_id', name='uq_duplicate_pair'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_duplicate_suspicions_identity_id'), 'duplicate_suspicions', ['identity_id'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_duplicate_suspicions_other_identity_id'), 'duplicate_suspicions', ['other_identity_id'], unique=False, schema='identity')
    op.create_table('appeals',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('filed_by', sa.UUID(), nullable=False),
    sa.Column('statement', sa.String(length=2000), nullable=False),
    sa.Column('case_status_at_filing', sa.String(length=20), nullable=False),
    sa.Column('original_reviewer_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['verification.cases.id'], name=op.f('fk_appeals_case_id_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appeals')),
    sa.UniqueConstraint('case_id', name=op.f('uq_appeals_case_id')),
    schema='verification'
    )
    op.create_index('ix_appeals_status', 'appeals', ['status', 'created_at'], unique=False, schema='verification')
    op.add_column('milestones', sa.Column('partial_offer_minor', sa.BigInteger(), nullable=True), schema='contract')
    op.add_column('milestones', sa.Column('partial_offer_reason', sa.String(length=1000), nullable=True), schema='contract')
    op.add_column('milestones', sa.Column('partial_offered_at', sa.DateTime(timezone=True), nullable=True), schema='contract')
    op.add_column('milestones', sa.Column('accepted_release_minor', sa.BigInteger(), nullable=True), schema='contract')
    op.add_column('professionals', sa.Column('weekly_hours', sa.Integer(), nullable=True), schema='professional')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professionals', 'weekly_hours', schema='professional')
    op.drop_column('milestones', 'accepted_release_minor', schema='contract')
    op.drop_column('milestones', 'partial_offered_at', schema='contract')
    op.drop_column('milestones', 'partial_offer_reason', schema='contract')
    op.drop_column('milestones', 'partial_offer_minor', schema='contract')
    op.drop_index('ix_appeals_status', table_name='appeals', schema='verification')
    op.drop_table('appeals', schema='verification')
    op.drop_index(op.f('ix_identity_duplicate_suspicions_other_identity_id'), table_name='duplicate_suspicions', schema='identity')
    op.drop_index(op.f('ix_identity_duplicate_suspicions_identity_id'), table_name='duplicate_suspicions', schema='identity')
    op.drop_table('duplicate_suspicions', schema='identity')
    # ### end Alembic commands ###
