"""saved buyers

Revision ID: af9206f2a9b9
Revises: b6db68c1e03a
Create Date: 2026-10-09 14:21:11.875838
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'af9206f2a9b9'
down_revision = 'b6db68c1e03a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_buyers',
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('alerts', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professional.professionals.id'], name=op.f('fk_saved_buyers_professional_id_professionals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_buyers')),
    sa.UniqueConstraint('professional_id', 'organization_id', name=op.f('uq_saved_buyers_professional_id_organization_id')),
    schema='professional'
    )
    op.create_index(op.f('ix_professional_saved_buyers_professional_id'), 'saved_buyers', ['professional_id'], unique=False, schema='professional')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professional_saved_buyers_professional_id'), table_name='saved_buyers', schema='professional')
    op.drop_table('saved_buyers', schema='professional')
    # ### end Alembic commands ###
