"""privacy request fulfilment and name erasure

Data requests gain their schedule, export file and outcome. Deletion requests made before this release (status
RECEIVED) are scheduled: 14 days after they were made, or at once if that has passed. Messages and reviews stay
append-only, except that a privacy erasure may replace the copied name with "Deleted user" (shared/ddl.py).

Revision ID: b6db68c1e03a
Revises: 68fb966363b4
Create Date: 2026-10-09 13:40:45.976884
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from zoikorum.shared.ddl import NAME_ERASURE_FN, name_erasure_trigger

revision = 'b6db68c1e03a'
down_revision = '68fb966363b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_requests', sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True), schema='identity')
    op.add_column('data_requests', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True), schema='identity')
    op.add_column('data_requests', sa.Column('export_key', sa.String(length=300), nullable=True), schema='identity')
    op.add_column('data_requests', sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False), schema='identity')
    # ### end Alembic commands ###
    op.execute("""
        UPDATE identity.data_requests
        SET status = 'SCHEDULED', scheduled_for = greatest(created_at + interval '14 days', now())
        WHERE request_type = 'ERASURE' AND status IN ('RECEIVED', 'IN_PROGRESS')
    """)
    op.execute("""
        INSERT INTO platform.timers (id, kind, key, fire_at, payload, attempts, created_at)
        SELECT gen_random_uuid(), 'identity.erasure_due', id::text, scheduled_for,
               jsonb_build_object('dataRequestId', id::text), 0, now()
        FROM identity.data_requests WHERE request_type = 'ERASURE' AND status = 'SCHEDULED'
        ON CONFLICT (kind, key) DO NOTHING
    """)
    op.execute(NAME_ERASURE_FN)
    for statement in name_erasure_trigger("messaging.messages") + name_erasure_trigger("review.reviews"):
        op.execute(statement)


def downgrade() -> None:
    for table in ("messaging.messages", "review.reviews"):
        schema, name = table.split(".")
        op.execute(f"DROP TRIGGER IF EXISTS trg_{name}_append_only ON {table}")
        op.execute(f"CREATE TRIGGER trg_{name}_append_only BEFORE UPDATE OR DELETE ON {table} "
                   "FOR EACH ROW EXECUTE FUNCTION platform.prevent_mutation()")
    op.execute("DROP FUNCTION IF EXISTS platform.prevent_mutation_except_name_erasure()")
    op.execute("DELETE FROM platform.timers WHERE kind = 'identity.erasure_due' AND fired_at IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_requests', 'detail', schema='identity')
    op.drop_column('data_requests', 'export_key', schema='identity')
    op.drop_column('data_requests', 'expires_at', schema='identity')
    op.drop_column('data_requests', 'scheduled_for', schema='identity')
    # ### end Alembic commands ###
