"""Governed AI, reporting projections and enforcement."""
from alembic import op

revision = "c8427d916a30"
down_revision = "b739e68210ad"
branch_labels = None
depends_on = None

def upgrade():
    op.execute('CREATE SCHEMA IF NOT EXISTS ai')
    op.execute('CREATE SCHEMA IF NOT EXISTS admin')
    op.execute('CREATE SCHEMA IF NOT EXISTS analytics')
    op.execute('\nCREATE TABLE ai.prompt_versions (\n\tprompt_key VARCHAR(60) NOT NULL, \n\tversion INTEGER NOT NULL, \n\towner UUID, \n\ttarget_model VARCHAR(100) NOT NULL, \n\tinstructions TEXT NOT NULL, \n\tgolden_tests JSONB NOT NULL, \n\tstatus VARCHAR(20) NOT NULL, \n\tapproved_by UUID, \n\tid UUID NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_prompt_versions PRIMARY KEY (id), \n\tCONSTRAINT uq_prompt_versions_prompt_key_version UNIQUE (prompt_key, version)\n)\n\n')
    op.execute('\nCREATE TABLE ai.inference_logs (\n\tprompt_id UUID, \n\tprompt_version INTEGER, \n\tmodel VARCHAR(100) NOT NULL, \n\tinput_sha256 VARCHAR(64) NOT NULL, \n\toutput TEXT NOT NULL, \n\tpurpose VARCHAR(60) NOT NULL, \n\tsubject_id UUID NOT NULL, \n\trequested_by UUID NOT NULL, \n\tlatency_ms INTEGER NOT NULL, \n\tfallback_used BOOLEAN NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_inference_logs PRIMARY KEY (id)\n)\n\n')
    op.execute('\nCREATE TABLE ai.risk_observations (\n\tsource_event_id UUID NOT NULL, \n\tidentity_id UUID NOT NULL, \n\tkind VARCHAR(40) NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_risk_observations PRIMARY KEY (id), \n\tCONSTRAINT uq_risk_observations_source_event_id UNIQUE (source_event_id)\n)\n\n')
    op.execute('\nCREATE TABLE admin.enforcement_cases (\n\tsubject_type VARCHAR(30) NOT NULL, \n\tsubject_id UUID NOT NULL, \n\tsource_event_id UUID, \n\tsignal_source VARCHAR(100) NOT NULL, \n\tsummary VARCHAR(2000) NOT NULL, \n\tevidence_refs JSONB NOT NULL, \n\tlevel INTEGER NOT NULL, \n\treason_code VARCHAR(100), \n\tstatus VARCHAR(30) NOT NULL, \n\taction VARCHAR(40), \n\tnotice JSONB, \n\topened_by UUID, \n\tproposed_by UUID, \n\tapprovals JSONB NOT NULL, \n\tduration_days INTEGER, \n\texpires_at TIMESTAMP WITH TIME ZONE, \n\tapplied_at TIMESTAMP WITH TIME ZONE, \n\treversed_by UUID, \n\tappeal JSONB, \n\tid UUID NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tversion BIGINT NOT NULL, \n\tCONSTRAINT pk_enforcement_cases PRIMARY KEY (id), \n\tCONSTRAINT uq_enforcement_cases_source_event_id UNIQUE (source_event_id)\n)\n\n')
    op.execute('\nCREATE TABLE analytics.event_facts (\n\tsource_event_id UUID NOT NULL, \n\tseq BIGINT GENERATED BY DEFAULT AS IDENTITY, \n\tevent_type VARCHAR(200) NOT NULL, \n\torganization_id UUID, \n\tprofessional_id UUID, \n\taggregate_id VARCHAR(100) NOT NULL, \n\tpayload JSONB NOT NULL, \n\toccurred_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_event_facts PRIMARY KEY (id), \n\tCONSTRAINT uq_event_facts_source_event_id UNIQUE (source_event_id), \n\tCONSTRAINT uq_event_facts_seq UNIQUE (seq)\n)\n\n')
    op.execute('CREATE INDEX ix_ai_risk_observations_identity_id ON ai.risk_observations (identity_id)')
    op.execute('CREATE INDEX ix_admin_enforcement_cases_subject_id ON admin.enforcement_cases (subject_id)')
    op.execute('CREATE INDEX ix_analytics_event_facts_professional_id ON analytics.event_facts (professional_id)')
    op.execute('CREATE INDEX ix_analytics_event_facts_organization_id ON analytics.event_facts (organization_id)')
    op.execute("\nCREATE OR REPLACE FUNCTION platform.prevent_mutation() RETURNS trigger AS $$\nBEGIN\n  RAISE EXCEPTION 'table %.% is append-only (% rejected)', TG_TABLE_SCHEMA, TG_TABLE_NAME, TG_OP\n    USING ERRCODE = 'insufficient_privilege';\nEND;\n$$ LANGUAGE plpgsql;\n")
    op.execute("CREATE OR REPLACE FUNCTION ai.guard_prompt() RETURNS trigger AS $$\n        BEGIN\n          IF TG_OP = 'DELETE' OR (OLD.status <> 'DRAFT' AND (NEW.prompt_key IS DISTINCT FROM OLD.prompt_key\n             OR NEW.version IS DISTINCT FROM OLD.version OR NEW.instructions IS DISTINCT FROM OLD.instructions\n             OR NEW.golden_tests IS DISTINCT FROM OLD.golden_tests OR NEW.target_model IS DISTINCT FROM OLD.target_model\n             OR NEW.approved_by IS DISTINCT FROM OLD.approved_by OR NEW.status <> 'RETIRED')) THEN\n             RAISE EXCEPTION 'approved prompt versions are immutable';\n          END IF;\n          RETURN NEW;\n        END; $$ LANGUAGE plpgsql;")
    op.execute('DROP TRIGGER IF EXISTS trg_prompt_immutable ON ai.prompt_versions;')
    op.execute('CREATE TRIGGER trg_prompt_immutable BEFORE UPDATE OR DELETE ON ai.prompt_versions FOR EACH ROW EXECUTE FUNCTION ai.guard_prompt();')
    op.execute("CREATE OR REPLACE FUNCTION dispute.guard_decision() RETURNS trigger AS $$\n        BEGIN\n          IF OLD.decision IS NOT NULL AND NEW.decision IS DISTINCT FROM OLD.decision THEN\n            RAISE EXCEPTION 'issued dispute decisions are immutable';\n          END IF;\n          RETURN NEW;\n        END; $$ LANGUAGE plpgsql;")
    op.execute('DROP TRIGGER IF EXISTS trg_decision_immutable ON dispute.cases;')
    op.execute('CREATE TRIGGER trg_decision_immutable BEFORE UPDATE ON dispute.cases FOR EACH ROW EXECUTE FUNCTION dispute.guard_decision();')
    op.execute("CREATE OR REPLACE FUNCTION dispute.guard_appeal() RETURNS trigger AS $$\n        BEGIN\n          IF TG_OP = 'DELETE' OR OLD.status <> 'PENDING' OR NEW.case_id IS DISTINCT FROM OLD.case_id\n            OR NEW.submitted_by IS DISTINCT FROM OLD.submitted_by OR NEW.grounds IS DISTINCT FROM OLD.grounds\n            OR NEW.explanation IS DISTINCT FROM OLD.explanation OR NEW.evidence IS DISTINCT FROM OLD.evidence THEN\n            RAISE EXCEPTION 'appeal submissions and issued decisions are immutable';\n          END IF;\n          RETURN NEW;\n        END; $$ LANGUAGE plpgsql;")
    op.execute('DROP TRIGGER IF EXISTS trg_appeal_immutable ON dispute.appeals;')
    op.execute('CREATE TRIGGER trg_appeal_immutable BEFORE UPDATE OR DELETE ON dispute.appeals FOR EACH ROW EXECUTE FUNCTION dispute.guard_appeal();')
    op.execute('DROP TRIGGER IF EXISTS trg_inference_logs_append_only ON ai.inference_logs;')
    op.execute('CREATE TRIGGER trg_inference_logs_append_only BEFORE UPDATE OR DELETE ON ai.inference_logs FOR EACH ROW EXECUTE FUNCTION platform.prevent_mutation();')

def downgrade():
    op.execute("DROP TRIGGER IF EXISTS trg_decision_immutable ON dispute.cases")
    op.execute("DROP TRIGGER IF EXISTS trg_appeal_immutable ON dispute.appeals")
    op.drop_table('event_facts', schema='analytics')
    op.drop_table('enforcement_cases', schema='admin')
    op.drop_table('risk_observations', schema='ai')
    op.drop_table('inference_logs', schema='ai')
    op.drop_table('prompt_versions', schema='ai')
