"""verification evidence content type

Revision ID: cc6512f38e47
Revises: ec12efe68c05
Create Date: 2026-10-07 13:41:31.250671
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'cc6512f38e47'
down_revision = 'ec12efe68c05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence_items', sa.Column('content_type', sa.String(length=100), nullable=True), schema='verification')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence_items', 'content_type', schema='verification')
    # ### end Alembic commands ###
