"""enterprise policies approvals and immutable versions

Revision ID: d04537c7a0f4
Revises: f20e9c85b704
Create Date: 2026-10-07 18:34:01.213996
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'd04537c7a0f4'
down_revision = 'f20e9c85b704'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE SCHEMA IF NOT EXISTS policy')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('policy_version_id', sa.UUID(), nullable=True),
    sa.Column('subject_type', sa.String(length=60), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('requester_identity_id', sa.UUID(), nullable=True),
    sa.Column('context_hash', sa.String(length=64), nullable=False),
    sa.Column('request_key', sa.String(length=64), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('workflows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('escalation_role', sa.String(length=30), nullable=False),
    sa.Column('escalation_count', sa.Integer(), nullable=False),
    sa.Column('step_up_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests')),
    sa.UniqueConstraint('request_key', name='uq_policy_approval_request_key'),
    schema='policy'
    )
    op.create_index('ix_policy_approvals_org_status', 'approval_requests', ['organization_id', 'status'], unique=False, schema='policy')
    op.create_table('exception_requests',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('policy_version_id', sa.UUID(), nullable=True),
    sa.Column('subject_type', sa.String(length=60), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('context_hash', sa.String(length=64), nullable=False),
    sa.Column('requester_identity_id', sa.UUID(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decision_reason', sa.String(length=1000), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exception_requests')),
    schema='policy'
    )
    op.create_index('ix_policy_exceptions_org_status', 'exception_requests', ['organization_id', 'status'], unique=False, schema='policy')
    op.create_table('policy_evaluations',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('policy_version_id', sa.UUID(), nullable=True),
    sa.Column('policy_profile_id', sa.UUID(), nullable=True),
    sa.Column('policy_version_label', sa.String(length=120), nullable=False),
    sa.Column('subject_type', sa.String(length=60), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('actor_identity_id', sa.UUID(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('context_hash', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=25), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_evaluations')),
    schema='policy'
    )
    op.create_index('ix_policy_evaluations_subject', 'policy_evaluations', ['organization_id', 'subject_id', 'action'], unique=False, schema='policy')
    op.create_table('profiles',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('business_unit_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active_version_id', sa.UUID(), nullable=True),
    sa.Column('draft_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles')),
    schema='policy'
    )
    op.create_index('ix_policy_profiles_org', 'profiles', ['organization_id'], unique=False, schema='policy')
    op.create_table('approval_votes',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.String(length=100), nullable=False),
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('authority_role', sa.String(length=30), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['policy.approval_requests.id'], name=op.f('fk_approval_votes_request_id_approval_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_votes')),
    sa.UniqueConstraint('request_id', 'identity_id', name='uq_policy_approval_vote'),
    schema='policy'
    )
    op.create_table('versions',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('activated_by', sa.UUID(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['policy.profiles.id'], name=op.f('fk_versions_profile_id_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_versions')),
    sa.UniqueConstraint('profile_id', 'number', name='uq_policy_version_number'),
    schema='policy'
    )
    op.add_column('contracts', sa.Column('policy_version_id', sa.UUID(), nullable=True), schema='contract')
    op.alter_column('contracts', 'policy_version_label',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False,
               schema='contract')
    op.add_column('proposals', sa.Column('policy_version_id', sa.UUID(), nullable=True), schema='proposal')
    op.add_column('requests', sa.Column('cost_center_id', sa.UUID(), nullable=True), schema='proposal')
    from zoikorum.shared import ddl
    for statement in ddl.all_statements({'policy.versions', 'policy.policy_evaluations', 'policy.approval_votes'}):
        op.execute(statement)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'cost_center_id', schema='proposal')
    op.drop_column('proposals', 'policy_version_id', schema='proposal')
    op.alter_column('contracts', 'policy_version_label',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False,
               schema='contract')
    op.drop_column('contracts', 'policy_version_id', schema='contract')
    op.drop_table('versions', schema='policy')
    op.drop_table('approval_votes', schema='policy')
    op.drop_index('ix_policy_profiles_org', table_name='profiles', schema='policy')
    op.drop_table('profiles', schema='policy')
    op.drop_index('ix_policy_evaluations_subject', table_name='policy_evaluations', schema='policy')
    op.drop_table('policy_evaluations', schema='policy')
    op.drop_index('ix_policy_exceptions_org_status', table_name='exception_requests', schema='policy')
    op.drop_table('exception_requests', schema='policy')
    op.drop_index('ix_policy_approvals_org_status', table_name='approval_requests', schema='policy')
    op.drop_table('approval_requests', schema='policy')
    # ### end Alembic commands ###
