"""proposals: requests and proposals

Revision ID: d4e6bc59f94f
Revises: 39eff2ff7220
Create Date: 2026-10-06 10:15:31.619646
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'd4e6bc59f94f'
down_revision = '39eff2ff7220'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE SCHEMA IF NOT EXISTS "proposal"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('buyer_identity_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('service', sa.String(length=200), nullable=False),
    sa.Column('specialization', sa.String(length=120), nullable=True),
    sa.Column('engagement_type', sa.String(length=20), nullable=False),
    sa.Column('business_context', sa.String(length=20), nullable=True),
    sa.Column('objective', sa.String(length=300), nullable=False),
    sa.Column('details', sa.String(length=1200), nullable=False),
    sa.Column('desired_start_date', sa.Date(), nullable=False),
    sa.Column('estimated_duration', sa.String(length=20), nullable=False),
    sa.Column('budget_min_minor', sa.BigInteger(), nullable=True),
    sa.Column('budget_max_minor', sa.BigInteger(), nullable=True),
    sa.Column('budget_currency', sa.String(length=3), nullable=True),
    sa.Column('delivery_mode', sa.String(length=10), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('nda_required', sa.Boolean(), nullable=False),
    sa.Column('nda_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason_code', sa.String(length=60), nullable=True),
    sa.Column('reason_note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests')),
    schema='proposal'
    )
    op.create_index('ix_requests_group', 'requests', ['group_id'], unique=False, schema='proposal')
    op.create_index('ix_requests_org', 'requests', ['organization_id', 'created_at'], unique=False, schema='proposal')
    op.create_index('ix_requests_professional', 'requests', ['professional_id', 'status', 'created_at'], unique=False, schema='proposal')
    op.create_table('proposals',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('buyer_identity_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('scope_alignment', sa.String(length=20), nullable=False),
    sa.Column('scope_notes', sa.String(length=1000), nullable=True),
    sa.Column('deliverables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('milestones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pricing_model', sa.String(length=20), nullable=False),
    sa.Column('total_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exclusions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('revision_requests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('reason_code', sa.String(length=60), nullable=True),
    sa.Column('reason_note', sa.String(length=500), nullable=True),
    sa.Column('terms_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['proposal.requests.id'], name=op.f('fk_proposals_request_id_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposals')),
    sa.UniqueConstraint('request_id', name=op.f('uq_proposals_request_id')),
    schema='proposal'
    )
    op.create_index('ix_proposals_org', 'proposals', ['organization_id', 'status'], unique=False, schema='proposal')
    op.create_index('ix_proposals_professional', 'proposals', ['professional_id', 'status'], unique=False, schema='proposal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_proposals_professional', table_name='proposals', schema='proposal')
    op.drop_index('ix_proposals_org', table_name='proposals', schema='proposal')
    op.drop_table('proposals', schema='proposal')
    op.drop_index('ix_requests_professional', table_name='requests', schema='proposal')
    op.drop_index('ix_requests_org', table_name='requests', schema='proposal')
    op.drop_index('ix_requests_group', table_name='requests', schema='proposal')
    op.drop_table('requests', schema='proposal')
    # ### end Alembic commands ###
