"""insurance requirement and verified jurisdictions

Revision ID: d94dfd86d326
Revises: 2eb440dab54e
Create Date: 2026-10-05 18:16:43.562679
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'd94dfd86d326'
down_revision = '2eb440dab54e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxonomy_nodes', sa.Column('requires_insurance', sa.Boolean(), server_default='false', nullable=False), schema='marketplace')
    op.add_column('professional_documents', sa.Column('verified_jurisdictions', postgresql.ARRAY(sa.String(length=2)), server_default='{}', nullable=False), schema='search')
    # ### end Alembic commands ###
    # Existing taxonomy: regulated specializations require professional indemnity insurance (as before).
    op.execute("UPDATE marketplace.taxonomy_nodes SET requires_insurance = regulated")
    # Fill verified_jurisdictions afterwards with: python -m zoikorum.cli reindex-search


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professional_documents', 'verified_jurisdictions', schema='search')
    op.drop_column('taxonomy_nodes', 'requires_insurance', schema='marketplace')
    # ### end Alembic commands ###
