"""request scope extras and saved searches

Revision ID: ec12efe68c05
Revises: ee2311556e76
Create Date: 2026-10-07 11:20:00.396158
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'ec12efe68c05'
down_revision = 'ee2311556e76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_searches',
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_searches')),
    sa.UniqueConstraint('identity_id', 'name', name=op.f('uq_saved_searches_identity_id_name')),
    schema='marketplace'
    )
    op.create_index(op.f('ix_marketplace_saved_searches_identity_id'), 'saved_searches', ['identity_id'], unique=False, schema='marketplace')
    op.add_column('requests', sa.Column('deliverables', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")), schema='proposal')
    op.add_column('requests', sa.Column('dependencies', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")), schema='proposal')
    op.add_column('requests', sa.Column('pricing_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")), schema='proposal')
    op.add_column('requests', sa.Column('payment_cadence', sa.String(length=20), nullable=True), schema='proposal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'payment_cadence', schema='proposal')
    op.drop_column('requests', 'pricing_preferences', schema='proposal')
    op.drop_column('requests', 'dependencies', schema='proposal')
    op.drop_column('requests', 'deliverables', schema='proposal')
    op.drop_index(op.f('ix_marketplace_saved_searches_identity_id'), table_name='saved_searches', schema='marketplace')
    op.drop_table('saved_searches', schema='marketplace')
    # ### end Alembic commands ###
