"""disputes and refunds

Revision ID: ee2311556e76
Revises: 50b4309ca1b3
Create Date: 2026-10-07 08:40:32.059911
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'ee2311556e76'
down_revision = '50b4309ca1b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE SCHEMA IF NOT EXISTS "dispute"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('contract_reference', sa.String(length=20), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('milestone_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('desired_outcome', sa.String(length=30), nullable=False),
    sa.Column('context', sa.String(length=1000), nullable=False),
    sa.Column('initiated_by', sa.UUID(), nullable=True),
    sa.Column('initiator_party', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('disputed_minor', sa.BigInteger(), nullable=False),
    sa.Column('evidence_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence_complete', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('direct_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mediator_identity_id', sa.UUID(), nullable=True),
    sa.Column('recommendation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pending_decision', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decision', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases')),
    sa.UniqueConstraint('reference', name=op.f('uq_cases_reference')),
    schema='dispute'
    )
    op.create_index('ix_dispute_cases_contract', 'cases', ['contract_id', 'status'], unique=False, schema='dispute')
    op.create_index(op.f('ix_dispute_cases_organization_id'), 'cases', ['organization_id'], unique=False, schema='dispute')
    op.create_index(op.f('ix_dispute_cases_professional_id'), 'cases', ['professional_id'], unique=False, schema='dispute')
    op.create_table('refunds',
    sa.Column('escrow_refund_id', sa.UUID(), nullable=False),
    sa.Column('payment_intent_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.UUID(), nullable=True),
    sa.Column('dispute_id', sa.UUID(), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_ref', sa.String(length=100), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds')),
    sa.UniqueConstraint('escrow_refund_id', name=op.f('uq_refunds_escrow_refund_id')),
    schema='payments'
    )
    op.create_index('ix_refunds_org', 'refunds', ['organization_id', 'created_at'], unique=False, schema='payments')
    op.create_table('evidence_items',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('party', sa.String(length=20), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['dispute.cases.id'], name=op.f('fk_evidence_items_case_id_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_items')),
    schema='dispute'
    )
    op.create_index(op.f('ix_dispute_evidence_items_case_id'), 'evidence_items', ['case_id'], unique=False, schema='dispute')
    op.create_table('resolution_proposals',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('party', sa.String(length=20), nullable=False),
    sa.Column('proposed_by', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('allocations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['dispute.cases.id'], name=op.f('fk_resolution_proposals_case_id_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resolution_proposals')),
    schema='dispute'
    )
    op.create_index(op.f('ix_dispute_resolution_proposals_case_id'), 'resolution_proposals', ['case_id'], unique=False, schema='dispute')
    op.create_table('timeline',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['dispute.cases.id'], name=op.f('fk_timeline_case_id_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline')),
    schema='dispute'
    )
    op.create_index(op.f('ix_dispute_timeline_case_id'), 'timeline', ['case_id'], unique=False, schema='dispute')
    # ### end Alembic commands ###

    # Dispute evidence is insert-only: reject UPDATE/DELETE at the database level (EP-05).
    from zoikorum.shared.ddl import append_only_trigger
    for stmt in append_only_trigger("dispute.evidence_items"):
        op.execute(stmt)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispute_timeline_case_id'), table_name='timeline', schema='dispute')
    op.drop_table('timeline', schema='dispute')
    op.drop_index(op.f('ix_dispute_resolution_proposals_case_id'), table_name='resolution_proposals', schema='dispute')
    op.drop_table('resolution_proposals', schema='dispute')
    op.drop_index(op.f('ix_dispute_evidence_items_case_id'), table_name='evidence_items', schema='dispute')
    op.drop_table('evidence_items', schema='dispute')
    op.drop_index('ix_refunds_org', table_name='refunds', schema='payments')
    op.drop_table('refunds', schema='payments')
    op.drop_index(op.f('ix_dispute_cases_professional_id'), table_name='cases', schema='dispute')
    op.drop_index(op.f('ix_dispute_cases_organization_id'), table_name='cases', schema='dispute')
    op.drop_index('ix_dispute_cases_contract', table_name='cases', schema='dispute')
    op.drop_table('cases', schema='dispute')
    # ### end Alembic commands ###
