"""identity and audit foundation

Revision ID: f40309763a19
Revises: 
Create Date: 2026-10-05 12:37:40.743486
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'f40309763a19'
down_revision = None
branch_labels = None
depends_on = None


SCHEMAS = ("platform", "identity", "audit")
APPEND_ONLY = ("audit.audit_records",)


def upgrade() -> None:
    for schema in SCHEMAS:
        op.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_records',
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('actor_type', sa.String(length=30), nullable=False),
    sa.Column('auth_strength', sa.String(length=20), nullable=True),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('object_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('causation_id', sa.String(length=100), nullable=True),
    sa.Column('policy_version', sa.String(length=100), nullable=True),
    sa.Column('evidence_hash', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_records')),
    sa.UniqueConstraint('hash', name=op.f('uq_audit_records_hash')),
    sa.UniqueConstraint('seq', name=op.f('uq_audit_records_seq')),
    sa.UniqueConstraint('source_event_id', name=op.f('uq_audit_records_source_event_id')),
    schema='audit'
    )
    op.create_index('ix_audit_correlation', 'audit_records', ['correlation_id'], unique=False, schema='audit')
    op.create_index('ix_audit_object', 'audit_records', ['object_type', 'object_id'], unique=False, schema='audit')
    op.create_index('ix_audit_tenant_time', 'audit_records', ['tenant_id', 'occurred_at'], unique=False, schema='audit')
    op.create_table('export_jobs',
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('record_count', sa.BigInteger(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('chain_head_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_jobs')),
    schema='audit'
    )
    op.create_table('identities',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('platform_roles', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('personas', sa.ARRAY(sa.String(length=30)), nullable=False),
    sa.Column('primary_persona', sa.String(length=30), nullable=True),
    sa.Column('signup_organization_name', sa.String(length=200), nullable=True),
    sa.Column('mfa_secret_enc', sa.String(length=500), nullable=True),
    sa.Column('mfa_enabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enterprise_federated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identities')),
    sa.UniqueConstraint('email', name=op.f('uq_identities_email')),
    schema='identity'
    )
    op.create_table('consumer_failures',
    sa.Column('consumer', sa.String(length=150), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=200), nullable=False),
    sa.Column('envelope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('financial', sa.Boolean(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consumer_failures')),
    sa.UniqueConstraint('consumer', 'event_id', name=op.f('uq_consumer_failures_consumer_event_id')),
    schema='platform'
    )
    op.create_table('idempotency_keys',
    sa.Column('scope', sa.String(length=300), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('scope', name=op.f('pk_idempotency_keys')),
    schema='platform'
    )
    op.create_table('inbox',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('consumer', sa.String(length=150), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbox')),
    sa.UniqueConstraint('consumer', 'event_id', name=op.f('uq_inbox_consumer_event_id')),
    schema='platform'
    )
    op.create_table('outbox',
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=200), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.Column('envelope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('seq', name=op.f('pk_outbox')),
    sa.UniqueConstraint('event_id', name=op.f('uq_outbox_event_id')),
    schema='platform'
    )
    op.create_index('ix_outbox_unpublished', 'outbox', ['seq'], unique=False, schema='platform', postgresql_where=sa.text('published_at IS NULL'))
    op.create_table('timers',
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('fire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timers')),
    sa.UniqueConstraint('kind', 'key', name=op.f('uq_timers_kind_key')),
    schema='platform'
    )
    op.create_index('ix_timers_due', 'timers', ['fire_at'], unique=False, schema='platform', postgresql_where=sa.text('fired_at IS NULL AND cancelled_at IS NULL'))
    op.create_table('consent_records',
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('document_version', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.identities.id'], name=op.f('fk_consent_records_identity_id_identities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent_records')),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_consent_records_identity_id'), 'consent_records', ['identity_id'], unique=False, schema='identity')
    op.create_table('identity_links',
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('roles', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.identities.id'], name=op.f('fk_identity_links_identity_id_identities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_links')),
    sa.UniqueConstraint('identity_id', 'link_type', 'target_id', name=op.f('uq_identity_links_identity_id_link_type_target_id')),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_identity_links_identity_id'), 'identity_links', ['identity_id'], unique=False, schema='identity')
    op.create_table('sessions',
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('auth_strength', sa.String(length=20), nullable=False),
    sa.Column('auth_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.identities.id'], name=op.f('fk_sessions_identity_id_identities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('refresh_token_hash', name=op.f('uq_sessions_refresh_token_hash')),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_sessions_family_id'), 'sessions', ['family_id'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_sessions_identity_id'), 'sessions', ['identity_id'], unique=False, schema='identity')
    # ### end Alembic commands ###

    # Insert-only tables: reject UPDATE/DELETE at the database level (EP-05).
    from zoikorum.shared.ddl import PREVENT_MUTATION_FN, append_only_trigger
    op.execute(PREVENT_MUTATION_FN)
    for table in APPEND_ONLY:
        for stmt in append_only_trigger(table):
            op.execute(stmt)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_sessions_identity_id'), table_name='sessions', schema='identity')
    op.drop_index(op.f('ix_identity_sessions_family_id'), table_name='sessions', schema='identity')
    op.drop_table('sessions', schema='identity')
    op.drop_index(op.f('ix_identity_identity_links_identity_id'), table_name='identity_links', schema='identity')
    op.drop_table('identity_links', schema='identity')
    op.drop_index(op.f('ix_identity_consent_records_identity_id'), table_name='consent_records', schema='identity')
    op.drop_table('consent_records', schema='identity')
    op.drop_index('ix_timers_due', table_name='timers', schema='platform', postgresql_where=sa.text('fired_at IS NULL AND cancelled_at IS NULL'))
    op.drop_table('timers', schema='platform')
    op.drop_index('ix_outbox_unpublished', table_name='outbox', schema='platform', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_table('outbox', schema='platform')
    op.drop_table('inbox', schema='platform')
    op.drop_table('idempotency_keys', schema='platform')
    op.drop_table('consumer_failures', schema='platform')
    op.drop_table('identities', schema='identity')
    op.drop_table('export_jobs', schema='audit')
    op.drop_index('ix_audit_tenant_time', table_name='audit_records', schema='audit')
    op.drop_index('ix_audit_object', table_name='audit_records', schema='audit')
    op.drop_index('ix_audit_correlation', table_name='audit_records', schema='audit')
    op.drop_table('audit_records', schema='audit')
    # ### end Alembic commands ###
