"""professional profiles and capability taxonomy

Revision ID: f7f280be35f1
Revises: 8b68282be96e
Create Date: 2026-10-05 15:00:12.818605
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from zoikorum.domains.marketplace.taxonomy_data import default_taxonomy_rows

revision = 'f7f280be35f1'
down_revision = '8b68282be96e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    for schema in ("marketplace", "professional"):
        op.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxonomy_nodes',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('category_slug', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('requires_credential', sa.Boolean(), nullable=False),
    sa.Column('regulated', sa.Boolean(), nullable=False),
    sa.Column('deliverable_templates', postgresql.ARRAY(sa.String(length=200)), nullable=False),
    sa.Column('credential_hints', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('taxonomy_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['marketplace.taxonomy_nodes.id'], name=op.f('fk_taxonomy_nodes_parent_id_taxonomy_nodes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taxonomy_nodes')),
    sa.UniqueConstraint('slug', name=op.f('uq_taxonomy_nodes_slug')),
    schema='marketplace'
    )
    op.create_index(op.f('ix_marketplace_taxonomy_nodes_category_slug'), 'taxonomy_nodes', ['category_slug'], unique=False, schema='marketplace')
    op.create_table('professionals',
    sa.Column('identity_id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('headline', sa.String(length=120), nullable=True),
    sa.Column('years_experience_band', sa.String(length=10), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('primary_category', sa.String(length=120), nullable=True),
    sa.Column('primary_specialization', sa.String(length=120), nullable=True),
    sa.Column('secondary_specializations', postgresql.ARRAY(sa.String(length=120)), nullable=False),
    sa.Column('engagement_types', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('delivery_modes', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('pricing_models', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('rate_minor', sa.BigInteger(), nullable=True),
    sa.Column('rate_currency', sa.String(length=3), nullable=True),
    sa.Column('rate_unit', sa.String(length=10), nullable=True),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('max_concurrent_engagements', sa.Integer(), nullable=True),
    sa.Column('temporarily_unavailable', sa.Boolean(), nullable=False),
    sa.Column('active_engagements', sa.Integer(), nullable=False),
    sa.Column('served_jurisdictions', postgresql.ARRAY(sa.String(length=2)), nullable=False),
    sa.Column('licensed_jurisdictions', postgresql.ARRAY(sa.String(length=2)), nullable=False),
    sa.Column('cross_border_acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accuracy_attested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('visibility_reduced', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professionals')),
    sa.UniqueConstraint('identity_id', name=op.f('uq_professionals_identity_id')),
    schema='professional'
    )
    op.create_table('credential_claims',
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('credential_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('issuing_body', sa.String(length=200), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('jurisdiction', sa.String(length=10), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('specialization', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professional.professionals.id'], name=op.f('fk_credential_claims_professional_id_professionals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credential_claims')),
    schema='professional'
    )
    op.create_index(op.f('ix_professional_credential_claims_professional_id'), 'credential_claims', ['professional_id'], unique=False, schema='professional')
    op.create_table('offerings',
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('specialization', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('deliverables', postgresql.ARRAY(sa.String(length=200)), nullable=False),
    sa.Column('engagement_types', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('pricing_model', sa.String(length=20), nullable=False),
    sa.Column('starting_price_minor', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('typical_duration', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professional.professionals.id'], name=op.f('fk_offerings_professional_id_professionals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offerings')),
    schema='professional'
    )
    op.create_index(op.f('ix_professional_offerings_professional_id'), 'offerings', ['professional_id'], unique=False, schema='professional')
    # ### end Alembic commands ###
    _seed_taxonomy()


def _seed_taxonomy() -> None:
    """Reference data: the Finance & Accounting taxonomy (stable uuid5 ids, safe to re-run)."""
    nodes = sa.table(
        'taxonomy_nodes',
        *(sa.column(c) for c in ('id', 'slug', 'name', 'level', 'parent_id', 'category_slug', 'sort_order',
                                 'requires_credential', 'regulated', 'deliverable_templates', 'credential_hints',
                                 'status', 'taxonomy_version')),
        schema='marketplace',
    )
    for row in default_taxonomy_rows():
        op.execute(postgresql.insert(nodes).values(**row).on_conflict_do_nothing(index_elements=['slug']))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professional_offerings_professional_id'), table_name='offerings', schema='professional')
    op.drop_table('offerings', schema='professional')
    op.drop_index(op.f('ix_professional_credential_claims_professional_id'), table_name='credential_claims', schema='professional')
    op.drop_table('credential_claims', schema='professional')
    op.drop_table('professionals', schema='professional')
    op.drop_index(op.f('ix_marketplace_taxonomy_nodes_category_slug'), table_name='taxonomy_nodes', schema='marketplace')
    op.drop_table('taxonomy_nodes', schema='marketplace')
    # ### end Alembic commands ###
