"""Blob storage adapter (Architecture 8.x: files live in object storage, databases keep only keys + hashes).

``LocalDiskStorage`` is the development implementation. An S3 implementation (Object Lock for evidence)
plugs in behind ``BlobStorage`` without changing domain code.
"""

from __future__ import annotations

from pathlib import Path
from typing import Protocol

from zoikorum.config import get_settings


class BlobStorage(Protocol):
    def put(self, key: str, data: bytes) -> None: ...
    def get(self, key: str) -> bytes | None: ...
    def delete(self, key: str) -> None: ...


class LocalDiskStorage:
    def __init__(self, root: str | Path):
        self.root = Path(root).resolve()

    def _path(self, key: str) -> Path:
        path = (self.root / key).resolve()
        if self.root not in path.parents:  # keys are generated by the app, but never trust a path
            raise ValueError("Invalid storage key")
        return path

    def put(self, key: str, data: bytes) -> None:
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)

    def get(self, key: str) -> bytes | None:
        path = self._path(key)
        return path.read_bytes() if path.is_file() else None

    def delete(self, key: str) -> None:
        self._path(key).unlink(missing_ok=True)


def get_storage() -> BlobStorage:
    return LocalDiskStorage(get_settings().storage_dir)
