"""Render the database schema as Markdown, straight from the SQLAlchemy models (so it never drifts).

    python -m zoikorum.cli schema-doc        # writes docs/DATABASE_SCHEMA.md
"""

from __future__ import annotations

import inspect

from zoikorum.main import load_domains
from zoikorum.shared import platform_models  # noqa: F401 - registers platform tables
from zoikorum.shared.db import DOMAIN_SCHEMAS, Base
from zoikorum.shared.ddl import APPEND_ONLY_TABLES


def _type(col) -> str:
    try:
        return str(col.type).replace("VARCHAR", "varchar").replace("TIMESTAMP WITHOUT TIME ZONE", "timestamp")
    except Exception:  # noqa: BLE001 - dialect-specific types without a generic string form
        return type(col.type).__name__


def _keys(col) -> str:
    keys = []
    if col.primary_key:
        keys.append("PK")
    for fk in col.foreign_keys:
        keys.append(f"FK → {fk.target_fullname}")
    if col.unique:
        keys.append("unique")
    if col.index:
        keys.append("indexed")
    return ", ".join(keys)


def render() -> str:
    load_domains()
    docs = {m.local_table.fullname: inspect.getdoc(m.class_) or "" for m in Base.registry.mappers}
    tables = sorted(Base.metadata.tables.values(), key=lambda t: (DOMAIN_SCHEMAS.index(t.schema), t.name))
    out = [
        "# Database schema",
        "",
        "<!-- Generated by `python -m zoikorum.cli schema-doc` from the SQLAlchemy models. Do not edit by hand. -->",
        "",
        "One PostgreSQL database, **one schema per domain** (bounded context). Tables never reference another",
        "domain's tables with foreign keys; cross-domain links are plain UUID columns. Every table has a UUID",
        "primary key (except platform infrastructure tables) and `created_at`; mutable tables also have `updated_at`.",
        "Tables marked **append-only** reject UPDATE and DELETE at the database level.",
        "Migrations: `backend/alembic/versions/` (`alembic upgrade head`).",
        "",
        "## Contents",
        "",
    ]
    schemas = [s for s in DOMAIN_SCHEMAS if any(t.schema == s for t in tables)]
    out += [f"- [{s}](#schema-{s}) — {sum(1 for t in tables if t.schema == s)} tables" for s in schemas]
    empty = [s for s in DOMAIN_SCHEMAS if s not in schemas]
    if empty:
        out += ["", f"Schemas reserved for domains not built yet: {', '.join(f'`{s}`' for s in empty)}."]
    for schema in schemas:
        out += ["", f'<a id="schema-{schema}"></a>', f"## Schema `{schema}`"]
        for t in (t for t in tables if t.schema == schema):
            out += ["", f"### `{t.fullname}`" + (" — append-only" if t.fullname in APPEND_ONLY_TABLES else "")]
            if docs.get(t.fullname):
                out += ["", docs[t.fullname].replace("\n", " ")]
            out += ["", "| Column | Type | Null | Keys / index |", "|---|---|---|---|"]
            out += [f"| `{c.name}` | {_type(c)} | {'yes' if c.nullable else 'no'} | {_keys(c)} |" for c in t.columns]
            uniques = [", ".join(col.name for col in con.columns) for con in t.constraints
                       if con.__class__.__name__ == "UniqueConstraint" and len(con.columns) > 1]
            if uniques:
                out += ["", "Unique together: " + "; ".join(f"({u})" for u in uniques)]
    return "\n".join(out) + "\n"
